-- GET_BOOKINFO(1, VAR1, VAR2, VAR3)
CREATE OR REPLACE PROCEDURE GET_BOOKINFO (
    IN_BOOKID IN NUMBER,
    OUT_BOOKNAME OUT VARCHAR,
    OUT_PUBLISHER OUT VARCHAR,
    OUT_PRICE OUT NUMBER
) AS
    -- %TYPE 사용 : 테이블명.컬럼명%TYPE
    -- 테이블의 컬럼 동일한 타입으로 선언
    V_BOOKID BOOK.BOOKID%TYPE;
    V_BOOKNAME BOOK.BOOKNAME%TYPE;  
    V_PUBLISHER BOOK.PUBLISHER%TYPE;
    V_PRICE BOOK.PRICE%TYPE;
BEGIN
    SELECT BOOKID, BOOKNAME, PUBLISHER, PRICE
      INTO V_BOOKID, V_BOOKNAME, V_PUBLISHER, V_PRICE
      FROM BOOK
     WHERE IN_BOOKID = BOOKID;
     
     OUT_BOOKNAME := V_BOOKNAME;
     OUT_PUBLISHER := V_PUBLISHER;
     OUT_PRICE := V_PRICE;
     
     DBMS_OUTPUT.PUT_LINE(V_BOOKID||':'||V_BOOKNAME||':'||V_PUBLISHER||':'||V_PRICE);
END;
--------------------------------------
-- GET_BOOKINFO(IN, OUT, OUT, OUT)
CREATE OR REPLACE PROCEDURE GET_BOOKINFO (
    IN_BOOKID IN NUMBER,
    OUT_BOOKNAME OUT VARCHAR,
    OUT_PUBLISHER OUT VARCHAR,
    OUT_PRICE OUT NUMBER
) AS
    -- %TYPE 사용 : 테이블명.컬럼명%TYPE
    -- 테이블의 컬럼 동일한 타입으로 선언
    V_BOOKID BOOK.BOOKID%TYPE;
    V_BOOKNAME BOOK.BOOKNAME%TYPE;  
    V_PUBLISHER BOOK.PUBLISHER%TYPE;
    V_PRICE BOOK.PRICE%TYPE;
BEGIN
    SELECT BOOKID, BOOKNAME, PUBLISHER, PRICE
      INTO V_BOOKID, V_BOOKNAME, V_PUBLISHER, V_PRICE
      FROM BOOK
     WHERE IN_BOOKID = BOOKID;
     
     OUT_BOOKNAME := V_BOOKNAME;
     OUT_PUBLISHER := V_PUBLISHER;
     OUT_PRICE := V_PRICE;
     
     DBMS_OUTPUT.PUT_LINE(V_BOOKID||':'||V_BOOKNAME||':'||V_PUBLISHER||':'||V_PRICE);
END;
--------------------------------
--
CREATE OR REPLACE PROCEDURE GET_BOOKINFO2 (
    IN_BOOKID IN NUMBER,
    OUT_BOOKNAME OUT VARCHAR,
    OUT_PUBLISHER OUT VARCHAR,
    OUT_PRICE OUT NUMBER
) AS

BEGIN
    SELECT BOOKNAME, PUBLISHER, PRICE
      INTO OUT_BOOKNAME, OUT_PUBLISHER, OUT_PRICE
      FROM BOOK
     WHERE IN_BOOKID = BOOKID;
     
     DBMS_OUTPUT.PUT_LINE(IN_BOOKID||':'||OUT_BOOKNAME||':'||OUT_PUBLISHER||':'||OUT_PRICE);
END;
--------------------------
-- GET_BOOKINFO 프로시저를 호출해서 OUT값 확인
CREATE OR REPLACE PROCEDURE GET_BOOKINFO_TEST 
(
    IN_BOOKID IN NUMBER
) AS 
    V_BOOKNAME BOOK.BOOKNAME%TYPE;
    V_PUBLISHER BOOK.PUBLISHER%TYPE;
    V_PRICE BOOK.PRICE%TYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('입력받은 값 : '||IN_BOOKID);
    
    -- GET_BOOKINFO 프로시저 실행(호출)
    GET_BOOKINFO (IN_BOOKID, V_BOOKNAME, V_PUBLISHER, V_PRICE);
    
    -- 받은 값(OUT) 화면 출력
    DBMS_OUTPUT.PUT_LINE('>>BOOKINFO_TEST 결과 : '||IN_BOOKID||':'||V_BOOKNAME||':'||V_PUBLISHER||':'||V_PRICE);
END;