SELECT ABS(-15) FROM DUAL;
SELECT CEIL(15.4) FROM DUAL;
SELECT COS(3.14159) FROM DUAL;                                          --  해당 숫자의 코사인값을 반환
SELECT FLOOR(15.7) FROM DUAL;
SELECT LOG(10, 100) FROM DUAL;
SELECT MOD(11, 4) FROM DUAL;
SELECT POWER(3, 2) FROM DUAL;
SELECT ROUND(15.7) FROM DUAL;
SELECT SIGN(-15) FROM DUAL;
SELECT TRUNC(15.7) FROM DUAL;
SELECT CHR(67) FROM DUAL;                                                   --  해당 숫자를 아스키코드 문자로 반환
SELECT ASCII('A') FROM DUAL;
SELECT CONCAT('HAPPY ', 'BIRTHDAY') FROM DUAL;
SELECT LOWER('Birthday') FROM DUAL;
SELECT LPAD('Page 1', 15, '*.') FROM DUAL;
SELECT LTRIM('Page 1', 'Pae') FROM DUAL;                                 
SELECT RTRIM('Page 1', 'e 1') FROM DUAL;                                 
SELECT REPLACE('JACK', 'J', 'BL') FROM DUAL;
SELECT RPAD('Page 1', 15, '*.') FROM DUAL;
SELECT SUBSTR('ABCDEFG', 3, 4) FROM DUAL;
SELECT TRIM(LEADING 0 FROM '00AA00') FROM DUAL;              -- LEADING 0 뭔지 모름
SELECT UPPER('Birthday') FROM DUAL;
SELECT INSTR('CORPORATE FLOOR', 'OR', 3, 2) FROM DUAL;
SELECT LENGTH('Birthday') FROM DUAL;
SELECT ADD_MONTHS('14/05/21', 1) FROM DUAL;
SELECT LAST_DAY(SYSDATE) FROM DUAL;
SELECT NEXT_DAY(SYSDATE, '화') FROM DUAL;
SELECT ROUND(SYSDATE) FROM DUAL;
SELECT SYSDATE FROM DUAL;
SELECT TO_CHAR(SYSDATE) FROM DUAL;
SELECT TO_CHAR(123) FROM DUAL;
SELECT TO_DATE('12 05 2014', 'DD MM YYYY') FROM DUAL;
SELECT TO_NUMBER('12.3') FROM DUAL;
SELECT DECODE(1, 1, 'aa', 'bb') FROM DUAL;                              --  DECODE(1,1,2,3) -> 1과 1이 같으면 2, 다르면 3
SELECT NULLIF(123, 345) FROM DUAL;                                         --  NULL(1,2) -> 1과 2가 같으면 NULL, 다르면 1
SELECT NVL(NULL, 123) FROM DUAL;
